### PR TITLE
add gencode reference

### PR DESCRIPTION
**Pull request by aopisco**
two new references added to the S3 bucket:
1. human genome gencode v30 + ERCC + ChrM
2. the one above + HAV_18F virus

### CODE REVIEW

**Comment by jamestwebber** [comment]
You can test this using the `--branch` option for `evros`:

```evros --branch aopisco-add-HAV18-homoERCC92 alignment.run_start_and_htseq ...```

If the corresponding files are in the right place (index `tgz` in `czbiohub-reference/STAR/` and `gtf` in `czbiohub-reference/velocyto/`)  it should work fine...

**Comment by aopisco** [comment]
@jamestwebber the branch seems to be working but the jobs are not able to succeed. there is a problem with the genome that I can't understand: https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEventViewer:group=/aws/batch/job;stream=aegea_util_aws_batch_jd_27f7c94e/default/17d12cfd-099d-4dfd-bfbb-7404762bdc51

**Comment by aopisco** [comment]
testing completed

**Comment by aopisco** [comment]
@jamestwebber what are the steps to make the new human ref available for 10X/cell ranger as well?

**Comment by jamestwebber** [comment]
That requires making a separate cellranger reference (`cellranger mkref`) and modifying the corresponding scripts.

**Pull request merged**
