### PR TITLE
merge Ashley sars grch38

### PR DESCRIPTION
**Pull request by aopisco**

### CODE REVIEW

**Comment by jamestwebber** [comment]
Can you add some info to the README about this genome?

Lily wrote up descriptions for all the available genomes, although it is a bit hard to read through them all. Might be nice to have a table as well.

**Comment by aopisco** [comment]
@AshDangerByrne can you do it?

**Comment by AshDangerByrne** [comment]
Hi, I will add something to the Read Me.

**Comment by jamestwebber** [comment]
> Hi, I will add something to the Read Me.

It looks like maybe your local repo wasn't up to date with Lily's recent changes. Could you fix the conflicts (@aopisco maybe you can help)?

**Review by jamestwebber — APPROVED** [review]

**Review by neevor — APPROVED** [review]

**Pull request merged**
