### PR TITLE
Added gencode.vM19.ERCC.SP1 gtf support

### PR DESCRIPTION
**Pull request by shayanhoss**

### CODE REVIEW

**Comment by jamestwebber** [comment]
It looks like `SP2` isn't in here yet? Maybe you haven't pushed it.

Also, we don't want those `.DS_store` files in here–those are from the OS X file browser. You can use `git rm` to remove them from your repo. I guess I should add that to `.gitignore`.

**Comment by shayanhoss** [comment]
Ahh I think my title was a typo. I added support for SP1 because that is the sparsity we have used in the past. I havent checked how the alignment differs with sparsity, if at all. `SP1` for now is fine

**Comment by shayanhoss** [comment]
I think I removed it.

**Comment by jamestwebber** [comment]
With the help of PyCharm I removed these. For reference the commands:

```shell
git rm --cached --force "utilities/.DS_Store"
git rm --cached --force "src/.DS_Store"
git rm --cached --force "src/utilities/.DS_Store"
```

**Comment by shayanhoss** [comment]
Good to know. Thank you!

**Pull request merged**
